---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: multus-cni
  namespace: kube-system
  labels:
    k8s-app: multus-cni
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: multus-cni
  template:
    metadata:
      labels:
        k8s-app: multus-cni
    spec:
      hostNetwork: true
      containers:
      - image: ccr.ccs.tencentyun.com/tke-cni/multus-cni:v0.0.3
        imagePullPolicy: Always
        name: multus-cni
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /host/var/lib/cni/networks
          name: cni-network-dir
      volumes:
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: cni-network-dir
        hostPath:
          path: /var/lib/cni/networks

