apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  containers:
  - command: ["sleep", "2300000"]
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
